import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBarMenu, { MenuItem } from "@/components/codeeditor/SideBarMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems: MenuItem[] = [
  {
    name: "Project Space 1",
    href: "#",
    subMenu: [
      { name: "Repository 1", href: "" },
      { name: "Repository 2", href: "" },
    ],
  },
  {
    name: "Project Space 2",
    href: "#",
    subMenu: [
      { name: "Repository 1", href: "" },
      { name: "Repository 2", href: "" },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-row`}
      >
        <SideBarMenu menuItems={menuItems} />
        {children}
      </body>
    </html>
  );
}
